In [31]:
import pandas as pd 
import numpy as np
import sklearn
import matplotlib.pyplot as pyplot
from matplotlib import style
from sklearn import linear_model, preprocessing
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pickle, os

In [32]:
#read the data in the csv
data = pd.read_csv('car.data')
print(data.head())

  buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc


In [37]:
# Initialize the LabelEncoder
le = preprocessing.LabelEncoder()

# List of all columns you want to encode
# print(list(data.columns.values))
columns_to_encode = list(data.columns.values)#['buying', 'maint', 'door', 'persons', 'lug_boot', 'safety', 'class']

# Apply LabelEncoder to each column
for column in columns_to_encode:
    data[column] = le.fit_transform(data[column])

# Define the target variable 'class' and features
x = data.drop(columns=['class']).values  # All features except 'class'
y = data['class'].values  # The 'class' column as target

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size=0.1)

# Print sample of training features and test labels
print("Training features:", x_train )  # Print first 5 rows of training features for example
print("Test labels:", y_test )  # Print first 5 rows of test labels for example

Training features: [[3 2 0 0 1 2]
 [2 1 3 2 1 1]
 [2 2 3 0 0 2]
 ...
 [3 2 3 2 1 2]
 [2 3 1 2 1 2]
 [0 0 0 2 1 2]]
Test labels: [2 2 2 3 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2
 2 2 0 2 0 0 0 2 2 3 2 2 2 2 0 2 2 0 2 2 2 2 0 2 1 2 0 2 1 3 2 2 2 2 2 2 3
 2 2 2 0 2 2 0 1 2 2 0 2 2 2 2 2 1 0 2 2 2 2 2 2 0 0 2 2 2 2 0 2 0 2 2 2 2
 3 2 2 0 2 2 2 2 2 2 2 0 1 2 0 0 2 2 2 2 2 2 0 2 2 2 2 0 2 0 2 0 2 2 0 2 2
 0 2 0 2 2 0 2 2 3 2 3 1 2 2 2 0 2 2 2 2 2 2 2 0 2]


In [39]:
model = KNeighborsClassifier(n_neighbors=9)
model.fit(x_train, y_train)
acc = model.score(x_test, y_test)
print(acc)
predicted = model.predict(x_test)
names = ["unacc", "acc", "good", "vgood"]

for x in range(len(predicted)):
    print("Predicted: ", names[predicted[x]], "Data: ", x_test[x], "Actual: ", names[y_test[x]])
    # Now we will we see the neighbors of each point in our testing data
    n = model.kneighbors([x_test[x]], 9, True)
    print("N: ", n)

0.9190751445086706
Predicted:  good Data:  [1 2 1 0 0 1] Actual:  good
N:  (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[ 341,  107, 1164, 1094, 1357, 1252, 1269, 1518,  305]]))
Predicted:  good Data:  [3 2 3 1 2 1] Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[1203,  925,  259,   55, 1149,  473, 1063,   17,   13]]))
Predicted:  good Data:  [3 0 1 2 1 1] Actual:  good
N:  (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[ 192,  987,  865,  270,   82, 1264,  109, 1133, 1430]]))
Predicted:  vgood Data:  [2 1 3 2 1 0] Actual:  vgood
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.41421356, 1.41421356, 1.41421356]]), array([[  37,  537,  979,  244, 1013,    1, 1127,  582, 1191]]))
Predicted:  good Data:  [2 0 1 0 0 2] Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        